CI: ignore errors in coveralls.io upload until it will be resolved properly
Also restoring some of the env.vars the way how I had them in Cirrus CI,
the commented out LUA_COVERAGE was discarded by PR.

For some reason the step which did work in Cirrus CI fails on GHA.

Failure log:
```
Traceback (most recent call last):
  File "/usr/local/bin/cpp-coveralls", line 8, in <module>
    sys.exit(run())
             ~~~^^
File
"/usr/local/lib/python3.13/dist-packages/cpp_coveralls/__init__.py",
line 103, in run
    cov_report = coverage.collect(args)
File
"/usr/local/lib/python3.13/dist-packages/cpp_coveralls/coverage.py",
line 471, in collect
    src_report['coverage'] = parse_gcov_file(args, fobj, gcov_path)
                             ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
File
"/usr/local/lib/python3.13/dist-packages/cpp_coveralls/coverage.py",
line 261, in parse_gcov_file
    line_num = int(line_num)
ValueError: invalid literal for int() with base 10: '40-block 2'
Error: Process completed with exit code 1.
```

Wild guess about possible causes:
- unexpected $PWD causing the cpp-coveralls to look at wrong file tree
and finding unrelated .gcov files
- rogue .gcov file in unexpected location with unexpected content (but
in-tree of project)
- different python version making `int(line_num)` fail with same content
- different gcov version producing different content (shouldn't this be
part of gcc:14 image? ie. very likely NOT the cause)

Also starting the debugging with adding PWD and dump of beginnings of
.gcov files in expected location, before tampering with the python
script itself to provide better idea what went wrong.