CI: trying to make coveralls.io upload work with GHA
Also enable coverage upload for pull requests, it should work as long as
coveralls token secret is available to the workflow.

And if upload was not skipped, then stop on error, don't ignore it
silently (again "should work").

First try with token available failed to upload due to git being unhappy
with user/group of the files, for some reason upload runs under
different user or triggers the extra check or something (it is set as
safe dir during checkout action, but maybe this is reset for each step
or I don't know)?

log:
```
...
Installing collected packages: urllib3, idna, future,
charset_normalizer, certifi, requests, cpp-coveralls

Successfully installed certifi-2026.4.22 charset_normalizer-3.4.7
cpp-coveralls-0.4.2 future-1.0.0 idna-3.15 requests-2.34.2 urllib3-2.7.0
WARNING: Running pip as the 'root' user can result in broken permissions
and conflicting behaviour with the system package manager, possibly
rendering your system unusable. It is recommended to use a virtual
environment instead: https://pip.pypa.io/warnings/venv. Use the
--root-user-action option if you know what you are doing and want to
suppress this warning.
fatal: detected dubious ownership in repository at
'/__w/sjasmplus/sjasmplus'
To add an exception for this directory, call:

	git config --global --add safe.directory /__w/sjasmplus/sjasmplus
Traceback (most recent call last):
  File "/usr/local/bin/cpp-coveralls", line 8, in <module>
    sys.exit(run())
             ~~~^^
File
"/usr/local/lib/python3.13/dist-packages/cpp_coveralls/__init__.py",
line 103, in run
    cov_report = coverage.collect(args)
File
"/usr/local/lib/python3.13/dist-packages/cpp_coveralls/coverage.py",
line 397, in collect
    report['service_number'] = report['git']['head']['rev_count']
                               ~~~~~~~~~~~~~^^^^^^^^
KeyError: 'head'
Error: Process completed with exit code 1.
```